services:
  - type: web
    name: mini-docs-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: PORT
        value: 10000
